/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bigd

import bigd.proto.Message


class App {
    val greeting: String
        get() {
        Message.getDescriptor()
         return ""
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
